### ISSUE TITLE
Episodes don't load in Celluloid

### ISSUE THREAD

**Issue by FGarciaDorador** [YogeshLamichhane/anime-terminal#2]
Hello YogeshLaminichhane,

I'm having this error when I try to watch an episode:
![image](https://user-images.githubusercontent.com/73644112/132748411-9879a787-acdc-4d9b-a150-c282b711358e.png)

I'm on manjaro and maybe a recent update broke something? Last week it was functioning perfectly.

Thanks.

**Comment by YogeshLamichhane** [comment]
Hi @FGarciaDorador,
Thanks for letting me know about it. I just checked the issue and came to know that the issue isn't due to the update but due to the change in the website it fetches (gogoanime).
The website gogoanime now redirects to another link before playing the video when we try to play the video.

The script would be soon updated after fixing the issue.
Keep a little patience.

**Comment by YogeshLamichhane** [comment]
Hi @FGarciaDorador 
Please check the script. I guess it's working now!
Sorry for a delay cause i was a bit busy because of my study and exams.
Thanks!

**Comment by FGarciaDorador** [comment]
Hello,
After pulling the update, now celluloid does not open after selecting the episode. Does it work for you?

Don't worry about the delay. Thanks!

**Comment by YogeshLamichhane** [comment]
Hi,
Thanks for your patience. Would you mind checking the script again. I think it's fine now!

**Comment by FGarciaDorador** [comment]
It works now, thanks for the work!
